### ISSUE TITLE
Issue about the mismatch between generated noisy images and original noisy images

### ISSUE THREAD

**Issue by alwaysuu** [onwn/C2N#8]
Hi,

I am interested in your paper which used GAN to model real camera noise.  When I tried to generate noisy images based on the provided pre-trained generator (C2N-SIDD_to_SIDD.ckpt), I observed that the generated noisy images from the clean ones generally cannot match the original noisy ones, e.g., either noiser or more clear than the original noisy images (I simply run the test_generate.py  and didn't modify other codes).   Could you please have a look about this issue?

The followings are some samples:

1: random crops from 0101_005_S6_00100_00050_4400_L of SIDD_Medium_Srgb. 
clean image:
![101_1](https://user-images.githubusercontent.com/48625631/187386064-efa636a0-af17-49b6-b576-d26229825630.png) ![101_10](https://user-images.githubusercontent.com/48625631/187387049-458b6161-937a-43de-bcd3-f92f601fb646.png)

noisy image:
![101_1](https://user-images.githubusercontent.com/48625631/187386728-f0b673b6-08b2-4f32-9ac0-2898562709b5.png) ![101_10](https://user-images.githubusercontent.com/48625631/187387213-0f519700-b812-486b-aed0-490e287724c1.png)

generated noisy image:
![101_1_generated](https://user-images.githubusercontent.com/48625631/187386855-a3b4c700-dbae-4412-89c8-0e8f2939f17a.png) ![101_10_generated](https://user-images.githubusercontent.com/48625631/187387287-ac3ecf95-d472-4741-9643-526e1219317f.png)

2: random crops from 0104_005_S6_03200_01600_4400_L of SIDD_Medium_Srgb. 
clean image:
![104_1](https://user-images.githubusercontent.com/48625631/187387576-4550b4e8-6f92-4581-a5c6-d640884cb790.png) ![104_10](https://user-images.githubusercontent.com/48625631/187387581-55e21f94-abf8-4099-9486-054c09937882.png)

noisy image:
![104_1](https://user-images.githubusercontent.com/48625631/187387622-014002f5-e299-4b99-8a1e-6bf6963fc480.png) ![104_10](https://user-images.githubusercontent.com/48625631/187387610-44893c0f-29e8-4df6-bca2-40176f0eecf1.png)

generated noisy image:
![104_1_generated](https://user-images.githubusercontent.com/48625631/187387680-bebefe28-9f42-43fc-90e4-257039e6ae74.png) ![104_10_generated](https://user-images.githubusercontent.com/48625631/187387684-9e05b041-1e5e-4de5-9653-4e54c403cb21.png)

**Comment by onwn** [comment]
Sorry for my late reply - The _G_ generates noise maps with random intensity(noise level) that is sampled form certain distribution, where we train it to resemble that of the whole training set(namely, SIDD here).
Hence, the generated noisy images may differ in its noise level with specific noisy pair. What we intend is the set of these generated samples be containing realistic noise distribution and be available for training the following model(a denoiser for this denoising task).
